services:
  postgres:
    image: postgres:15
    container_name: postgres
    mem_limit: 512m
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    mem_limit: 512m
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - my_network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    mem_limit: 512m
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "MyCluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - my_network

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-server
    restart: always
    volumes:
      - prefect_data:/root/.prefect
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    ports:
      - "4200:4200"
    entrypoint: ["prefect", "server", "start"]
    depends_on:
      - postgres
    networks:
      - my_network

  # Prefect Worker
  prefect-worker:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-worker
    restart: always
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./flows:/opt/prefect/flows
      - ./data:/opt/prefect/data
      - prefect_data:/root/.prefect
    command: >
      bash -c "
        pip install psycopg2-binary kafka-python fastavro pandas &&
        prefect work-pool create --type process default-pool || true &&
        cd /opt/prefect/flows &&
        prefect deploy --all &&
        prefect worker start --pool default-pool
      "
    depends_on:
      - prefect-server
    networks:
      - my_network

volumes:
  postgres_data:
  prefect_data:

networks:
  my_network:
    driver: bridge